# Generated by Django 6.0.3 on 2026-03-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChainTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_index', models.CharField(max_length=100)),
                ('c_timestamp', models.CharField(max_length=100)),
                ('c_sender', models.CharField(max_length=100)),
                ('c_recipient', models.CharField(max_length=100)),
                ('c_amount', models.CharField(max_length=100)),
                ('c_proof', models.CharField(max_length=100)),
                ('c_previous_hash', models.CharField(max_length=100)),
                ('p_index', models.CharField(max_length=100)),
                ('p_timestamp', models.CharField(max_length=100)),
                ('p_sender', models.CharField(max_length=100)),
                ('p_recipient', models.CharField(max_length=100)),
                ('p_amount', models.CharField(max_length=100)),
                ('p_proof', models.CharField(max_length=100)),
                ('p_previous_hash', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BlockChainTransactiontable',
            },
        ),
        migrations.CreateModel(
            name='BuyerCropCartModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerusername', models.CharField(max_length=100)),
                ('buyeruseremail', models.CharField(max_length=100)),
                ('sellername', models.CharField(max_length=100)),
                ('cropname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100000)),
                ('price', models.FloatField()),
                ('file', models.FileField(upload_to='files/')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'BuyerCartTable',
            },
        ),
        migrations.CreateModel(
            name='BuyerTransactionModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyername', models.CharField(max_length=100)),
                ('totalamount', models.FloatField()),
                ('recipientname', models.CharField(max_length=100)),
                ('cradnumber', models.IntegerField()),
                ('nameoncard', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
                ('cardexpiry', models.CharField(max_length=200)),
                ('trnx_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BuyerTransactionTable',
            },
        ),
        migrations.CreateModel(
            name='BuyerUserRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('locality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BuyersRegistrations',
            },
        ),
    ]
