# Generated by Django 6.0.3 on 2026-03-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_username', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('order_id', models.IntegerField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BuyerNotifications',
            },
        ),
    ]
